name: user-statistician

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4

    - name: Generate the user stats image
      uses: cicirello/user-statistician@v1
      with:
        colors: light
        show-border: false
        top-icon: none
        custom-title: My GitHub Statistics
        hide-keys: joined, followers, following
        max-languages: 100
        animated-language-chart: false
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
