name: user-statistician

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4

    - name: Generate the user stats image
      uses: cicirello/user-statistician@v1
      with:
        colors: light
        show-border: false
        top-icon: none
        custom-title: Rinc's GitHub Statistics
        hide-keys: general, contributions, repositories, joined, followers, following
        language-repository-exclusions: AND-WebP
        max-languages: 15
        animated-language-chart: false
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
